{
    "dashscope/qwen3-coder-plus-2025-09-23": {
        "litellm_provider": "dashscope",
        "max_input_tokens": 997952,
        "max_output_tokens": 65536,
        "max_tokens": 1000000,
        "mode": "chat",
        "source": "https://www.alibabacloud.com/help/en/model-studio/models",
        "supports_function_calling": true,
        "supports_reasoning": true,
        "supports_tool_choice": true,
        "tiered_pricing": [
            {
                "cache_read_input_token_cost": 1e-07,
                "input_cost_per_token": 1e-06,
                "output_cost_per_token": 5e-06,
                "range": [
                    0,
                    32000.0
                ]
            },
            {
                "cache_read_input_token_cost": 1.8e-07,
                "input_cost_per_token": 1.8e-06,
                "output_cost_per_token": 9e-06,
                "range": [
                    32000.0,
                    128000.0
                ]
            },
            {
                "cache_read_input_token_cost": 3e-07,
                "input_cost_per_token": 3e-06,
                "output_cost_per_token": 1.5e-05,
                "range": [
                    128000.0,
                    256000.0
                ]
            },
            {
                "cache_read_input_token_cost": 6e-07,
                "input_cost_per_token": 6e-06,
                "output_cost_per_token": 6e-05,
                "range": [
                    256000.0,
                    1000000.0
                ]
            }
        ]
    },
    "gemini-3-5-flash-fair": {
        "litellm_provider": "openai",
        "mode": "chat",
        "max_input_tokens": 1048576,
        "max_output_tokens": 65535,
        "max_tokens": 65535,
        "input_cost_per_token": 1.5e-06,
        "output_cost_per_token": 9e-06,
        "output_cost_per_reasoning_token": 9e-06,
        "cache_read_input_token_cost": 1.5e-07,
        "source": "miscellaneous"
    },
    "gpt-5-5-genai-responses": {
        "litellm_provider": "openai",
        "mode": "responses",
        "max_input_tokens": 1050000,
        "max_output_tokens": 128000,
        "max_tokens": 128000,
        "input_cost_per_token": 5e-06,
        "output_cost_per_token": 3e-05,
        "cache_read_input_token_cost": 5e-07,
        "source": "miscellaneous"
    }
}
